
insert into  employee(emp_designation, emp_name, emp_salary) values ('founder', 'fvDavid Tobing', 120.0)
insert into  employee(emp_designation, emp_name, emp_salary) values ('co-founder', 'Saddam', 9000.0)

insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Jack Smith', 222.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Adam Goblin', 890.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Owen Case', 430.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Jave Bratt', 440.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Ogi Orc', 469.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Levite', 550.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('designer', 'Jessica Orz', 590.0)

insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Lemmima Zuh', 430.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Gerrand Llon', 440.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Chelsea Meano', 469.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Heileend', 550.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Gian Son', 590.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Ferr Hyuumon', 440.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Oakas Stund', 469.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('content writer', 'Merley Jackson', 550.0)

insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Angelina', 1422.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Mossosome', 1555.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Hyuna hombing', 980.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Don Parleon', 999.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Yong Guang', 1190.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Merky Youtter', 1290.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Zamboar Doan', 1155.0)
insert into employee (emp_designation, emp_name, emp_salary) values ('web Developer', 'Camila Diaz', 890.0)
